In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Encoding Technique
* OneHot Encoding

In [2]:
documents=['people watch movie,'
'people watch cricket',
'people like movie',
'people like cricket']

In [3]:
token=[i.lower().split() for i in documents]

In [4]:
token

[['people', 'watch', 'movie,people', 'watch', 'cricket'],
 ['people', 'like', 'movie'],
 ['people', 'like', 'cricket']]

In [5]:
all_words=[[word] for sentence in token for word in sentence]

In [6]:
all_words

[['people'],
 ['watch'],
 ['movie,people'],
 ['watch'],
 ['cricket'],
 ['people'],
 ['like'],
 ['movie'],
 ['people'],
 ['like'],
 ['cricket']]

In [12]:
encode=OneHotEncoder(sparse_output=False)

In [13]:
x=encode.fit_transform(all_words)

In [15]:
x

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.]])

In [11]:
import pandas as pd

In [17]:
data=pd.DataFrame(x,columns=encode.get_feature_names_out(['all_words']))

In [18]:
data

,all_words_cricket,all_words_like,all_words_movie,"all_words_movie,people",all_words_people,all_words_watch
0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0
4,1.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,1.0,0.0
6,0.0,1.0,0.0,0.0,0.0,0.0
7,0.0,0.0,1.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,1.0,0.0
9,0.0,1.0,0.0,0.0,0.0,0.0
10,1.0,0.0,0.0,0.0,0.0,0.0

# Bag of Words

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [1]:
documents=['people watch movie,'
'people watch cricket',
'people like movie',
'people like cricket']

In [4]:
vect=CountVectorizer()

In [6]:
wob=vect.fit_transform(documents)

In [7]:
wob.toarray()

array([[1, 0, 1, 2, 2],
       [0, 1, 1, 1, 0],
       [1, 1, 0, 1, 0]], dtype=int64)

In [8]:
vect.get_feature_names_out()

array(['cricket', 'like', 'movie', 'people', 'watch'], dtype=object)

In [9]:
import pandas as pd

In [11]:
wob_document_data=pd.DataFrame(wob.toarray(),columns=vect.get_feature_names_out())

In [12]:
wob_document_data

   cricket  like  movie  people  watch
0        1     0      1       2      2
1        0     1      1       1      0
2        1     1      0       1      0

# TF - IDF

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [14]:
vect=TfidfVectorizer()

In [19]:
documents=['people watch movie',
'people watch cricket',
'people like movie',
'people like cricket']

In [20]:
tfidf_doc=vect.fit_transform(documents)

In [21]:
tfidf_doc.toarray()

array([[0.        , 0.        , 0.64043405, 0.42389674, 0.64043405],
       [0.64043405, 0.        , 0.        , 0.42389674, 0.64043405],
       [0.        , 0.64043405, 0.64043405, 0.42389674, 0.        ],
       [0.64043405, 0.64043405, 0.        , 0.42389674, 0.        ]])

In [22]:
vect.get_feature_names_out()

array(['cricket', 'like', 'movie', 'people', 'watch'], dtype=object)